version: "3.9"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: taskmate-db
    restart: always
    environment:
      - SA_PASSWORD=${DB_SA_PASSWORD}
      - ACCEPT_EULA=${ACCEPT_EULA}
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql

  backend:
    build:
      context: ./backend/TaskMate.API
    container_name: taskmate-backend
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING}
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
      - Jwt__ExpiresInHours=${JWT_EXPIRES_IN_HOURS}
    ports:
      - "5048:8080"

  frontend:
    build:
      context: ./frontend
    container_name: taskmate-frontend
    depends_on:
      - backend
    environment:
      - VITE_API_URL=${VITE_API_URL}
    ports:
      - "5173:5173"

volumes:
  db_data: